# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-10 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyExngApp', '0002_auto_20200510_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recieved_curr',
            new_name='recieved_curr_code',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sent_curr',
            new_name='sent_curr_code',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='currency',
            new_name='currency_code',
        ),
    ]
