# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-10 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyExngApp', '0003_auto_20200510_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recieved_ammount',
            new_name='recieved_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sent_ammount',
            new_name='sent_amount',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='ammount',
            new_name='amount',
        ),
    ]
