# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-10 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyExngApp', '0004_auto_20200510_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciept_pdf',
            field=models.FileField(blank=True, help_text='Reciept PDF', null=True, upload_to='files'),
        ),
    ]
